'use strict';

const fs = require('fs');
const path = require('path');

const CONTENT = `# Generated by cpp-style-enforcer — Google C++ Style
BasedOnStyle: Google
IndentWidth: 2
NamespaceIndentation: None
`;

/**
 * 走全套流程且项目根缺少 .clang-format 时，生成一份 Google 风格配置。
 * 让 VS / clangd / 本插件三方读同一份配置，风格一致。
 *
 * - root 为 null（非 git）→ 不生成（无可靠项目根概念）。
 * - 已存在 .clang-format 或 _clang-format（Windows 兼容名）→ 绝不覆盖，直接返回。
 * - 写文件 UTF-8 无 BOM、LF；失败 try/catch 不崩。
 *
 * @param {string|null} root git 仓库根
 */
function ensureClangFormatConfig(root) {
  if (!root) return;
  try {
    // clang-format 向父目录继承配置；不要新建根配置遮盖已经适用的风格。
    let current = path.resolve(root);
    while (true) {
      if (fs.existsSync(path.join(current, '.clang-format'))
          || fs.existsSync(path.join(current, '_clang-format'))) return;
      const parent = path.dirname(current);
      if (parent === current) break;
      current = parent;
    }
    fs.writeFileSync(path.join(root, '.clang-format'), Buffer.from(CONTENT, 'utf-8'), { flag: 'wx' });
  } catch (_) {
    // 生成失败不影响主流程
  }
}

module.exports = { ensureClangFormatConfig };
